### ISSUE TITLE
isDot() is not a method

### ISSUE THREAD

**Issue by torvista** [lat9/notifier_report#2]
![Clipboard01](https://user-images.githubusercontent.com/4391026/116267602-da965280-a77c-11eb-9cff-b067bc17d5e2.gif)

https://stackoverflow.com/questions/6337810/why-does-isdot-fail-on-me-php

followed by brain freeze.

However, it is working on php8.

**Comment by lat9** [comment]
I'm not seeing that running on PHP 7.3.12.  What version of PHP are you running?

**Comment by torvista** [comment]
This is flagged by phpstorm inspection, from 5.6 to 8.
isDot is in DirectoryIterator but not RecursiveDirectoryIterator, or so I've heard.

**Comment by lat9** [comment]
False positive:

![image](https://user-images.githubusercontent.com/2685585/116579284-3c230200-a8e0-11eb-9f16-05e93001cd80.png)
![image](https://user-images.githubusercontent.com/2685585/116579389-58bf3a00-a8e0-11eb-8641-180890ee8d09.png)
![image](https://user-images.githubusercontent.com/2685585/116579528-77bdcc00-a8e0-11eb-895b-7affc52e42da.png)

**Comment by torvista** [comment]
I can't imagine how I didn't spot that :dizzy_face:

**Comment by torvista** [comment]
...as far as I understand, $it is of class RecursiveIteratorIterator, which is not extending RecursiveDirectoryIterator, so does not have access to that method.??
https://youtrack.jetbrains.com/issue/WI-60209

**Comment by lat9** [comment]
```php
$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator(DIR_FS_CATALOG));
```

$it is a class of a RecursiveIteratorIterator, using the RecursiveDirectoryIterator's result for its processing.  That's why `isDot` is a valid method.

**Comment by torvista** [comment]
I'll admit I don't have the nuances of classes at my fingertips, but I understand that
 if RecursiveIteratorIterator was extending 
 RecursiveDirectoryIterator it would have access to the methods two parent classes above RecursiveDirectoryIterator.
But does the same apply when RecursiveIteratorIterator is using a result, and not extending?

**Comment by lat9** [comment]
If it wasn't extending, we'd be getting PHP errors (as opposed to the JetBrains notification) when the script's run.
